### ISSUE TITLE
Request: Autodispose subscriptions when disposing an IStreamStore instance.

### ISSUE THREAD

**Issue by yreynhout** [damianh/SqlStreamStore#48]
# Problem space

At the moment, when one disposes a stream store instance, subscriptions find out about this fact when they try to read the next page from the specified stream store instance. The end users using the `IAllStreamSubscription SubscribeToAll(long? continueAfterPosition, AllStreamMessageReceived streamMessageReceived, AllSubscriptionDropped subscriptionDropped = null, HasCaughtUp hasCaughtUp = null, string name = null)` part of the API to set up these subscriptions, get notified about this via the `AllSubscriptionDropped` callback, which has the following signature `delegate void AllSubscriptionDropped(IAllStreamSubscription subscription, SubscriptionDroppedReason reason, Exception exception = null)`. The `SubscriptionDroppedReason` is `StreamStoreError` in this particular case, not `Disposed`, which is reserved for dropping the subscription itself (AFAICT). In order to figure out whether one should resubscribe, one has to inspect - next to the reason - the exception and figure out whether it is an `ObjectDisposedException` with an `ObjectName` property that matches the name of the specific `IStreamStore` implementation. It should go without saying that this is a bit leaky and difficult to figure out. Please note, I have not investigated the subscription to a specific stream. Wild guess is, it behaves pretty much the same.

In essence, it should be clear and easy to figure out when resubscribing is appropriate and when it is not.

# Solution space

- **IF** a stream store were to track and dispose of its subscriptions, the `SubscriptionDroppedReason` could become `Disposed` again, since that is effectively what would be going on. 
- A simpler, short term solution _might_ be to make the `SubscriptionDroppedReason` less ambiguous, namely:
```
  public enum SubscriptionDroppedReason
  {
    SubscriptionDisposed,
    StreamStoreDisposed,
    SubscriberError,
    StreamStoreError,
  }
```

**Comment by damianh** [comment]
I like. Thanks for writing this up @yreynhout

**Comment by damianh** [comment]
If I understand you right, when the store is disposed and it disposes of the subscriptions `SubscriptionDroppedReason.Disposed` is fine? You don't see a need for `StreamStoreDisposed` even when tracking is done?

**Comment by yreynhout** [comment]
Indeed, if tracking and auto dispose is done by the store, we don't need need the short term solution.

**Comment by damianh** [comment]
> Whether the subscription is being disposed implicitly or explicitly seems less interesting.

Agreed. While trivial to do this now, I'll wait for a use case.
