### ISSUE TITLE
Limit message payload size, or not?

### ISSUE THREAD

**Issue by damianh** [damianh/SqlStreamStore#55]
Currently the `JsonData` payload in `NewStreamMessage` is unbounded. Or rather, it is bounded to the limits the underlying store can support. For MsSQL server (`nvarchar(max)`, `text`) is rather large. This allows other patterns such as storing "documents" in the streams. However, EventStore has a limit of 64KB per message. Not having this limit further reduces portability.

While full portability with GES is not a goal, I thought that mentioning this decision here would be a good idea. :)

At this moment my preference is not to limit the size, but leave that to the user, if they so need it.

**Comment by danbarua** [comment]
👍 for no limits - PGSQL has `jsonb` for efficient binary-encoded JSON.

**Comment by jruizaranguren** [comment]
Vote for having 64KB as an overridable default limit. That way you make GES portability more explicit to consumers, and also put a boundary forcing people to think. You might want to deal with bigger files in a different way.

**Comment by damianh** [comment]
GES limit is actually 4MB or or similar. So no, not going to limit the size; consumers will have to make appropriate decisions for themselves. Will re-open later if it really appears to need it in practice.
