### ISSUE TITLE
SqlStreamStore.MsSql does not support netcoreapp1.1/netstandard 1.6

### ISSUE THREAD

**Issue by BennieCopeland** [damianh/SQLStreamStore#56]
I'm developing a dotnet core netcoreapp1.1 web application and am unable to add the SqlStreamStore.MsSql library as it is not compatible.

**Comment by BennieCopeland** [comment]
I took a quick look at converting the projects to dotnet after first opening this and ran into the issue of Nito.AsyncEx not supporting the netstandard. I dug more into it today, and it looks like the owner has split the project up into [smaller projects](https://github.com/StephenCleary/AsyncEx/issues/60). The [Nito.AsyncEx.Cooridination](https://www.nuget.org/packages/Nito.AsyncEx.Coordination) package appears to have the two types being used ```AsynceAutoResetEvent``` and ```TaskCompletionSource```. I'll see if I can get this building for dotnet core with the updated dependency and provide an update.

**Comment by damianh** [comment]
NetStandard support on merged to master. CI builds on https://www.myget.org/F/cedar/api/v3/index.json shortly so you can test the packages.
