### ISSUE TITLE
Question: will you be supprting linking a message to multiple streams?

### ISSUE THREAD

**Issue by jsharland** [damianh/SQLStreamStore#72]
Hi, I see that you are basing the SqlStreamStore on GetEventStore and I was wondering if you were planing on supporting the functionality to link a message created in one stream into another stream as can be done in GetEventStore using javascript projections?

We are quite keen to move away from GetEventStore and to use SqlStreamStore in its place so as to get the advantages of Sql Server, and this is one possible issue that may delay our adoption.

**Comment by damianh** [comment]
No, I have no plans to do that. Nor, at this time, can I see that happening. SqlStreamStore is a _library_ whose API is aligned (and diverts in placee) with GetEventStore. Adding such functionality will add significant complexity which will move it towards being an application server and I have no desire to go there. (If someone else, forks and does that, fair play).

For what you are looking for, GetEventStore is the best option.
